layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  exclude:
    archived: false
    forks: true
    projects:
      #- B2-18-init
  limit: 3

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: hrjakobsen
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: hrjakobsen
  # unsplash: your_username
  # vk: your_username
  website: https://aaq.dk
  website_uni: https://www.gla.ac.uk/pgrs/mathiassteenjakobsen/
  # youtube: your_username

topics:
  
